tup1=("C","D","A","A","B","B","A")
tup1.count("C")
tup1.count("D")
tup1.count("A")
tup1.count("B")
print("A=", tup1.count("A"))
print("B=", tup1.count("B"))
print("C=", tup1.count("C"))
print("D=", tup1.count("D"))
